// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type ActivateWarrantyControllerActivateWarrantyRequest struct {
	// Unique id of the warranty
	WarrantyID                         string                                        `pathParam:"style=simple,explode=false,name=warrantyId"`
	ActivateWarrantyCommandRequestBody components.ActivateWarrantyCommandRequestBody `request:"mediaType=application/json"`
}

func (o *ActivateWarrantyControllerActivateWarrantyRequest) GetWarrantyID() string {
	if o == nil {
		return ""
	}
	return o.WarrantyID
}

func (o *ActivateWarrantyControllerActivateWarrantyRequest) GetActivateWarrantyCommandRequestBody() components.ActivateWarrantyCommandRequestBody {
	if o == nil {
		return components.ActivateWarrantyCommandRequestBody{}
	}
	return o.ActivateWarrantyCommandRequestBody
}

type ActivateWarrantyControllerActivateWarrantyResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	ActivateWarrantyCommandResponse *components.ActivateWarrantyCommandResponse
}

func (o *ActivateWarrantyControllerActivateWarrantyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ActivateWarrantyControllerActivateWarrantyResponse) GetActivateWarrantyCommandResponse() *components.ActivateWarrantyCommandResponse {
	if o == nil {
		return nil
	}
	return o.ActivateWarrantyCommandResponse
}
