// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CloseClaimCommandControllerCloseRequest struct {
	// Unique identifier of the claim associated with the claim item.
	ClaimID string `pathParam:"style=simple,explode=false,name=claimId"`
}

func (o *CloseClaimCommandControllerCloseRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

type CloseClaimCommandControllerCloseResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	CloseClaimCommandResponse *components.CloseClaimCommandResponse
}

func (o *CloseClaimCommandControllerCloseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CloseClaimCommandControllerCloseResponse) GetCloseClaimCommandResponse() *components.CloseClaimCommandResponse {
	if o == nil {
		return nil
	}
	return o.CloseClaimCommandResponse
}
