// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreateCoverageControllerCreateCoverageResponse struct {
	HTTPMeta                      components.HTTPMetadata `json:"-"`
	CreateCoverageCommandResponse *components.CreateCoverageCommandResponse
}

func (o *CreateCoverageControllerCreateCoverageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCoverageControllerCreateCoverageResponse) GetCreateCoverageCommandResponse() *components.CreateCoverageCommandResponse {
	if o == nil {
		return nil
	}
	return o.CreateCoverageCommandResponse
}
