// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreatePolicyPlanCommandControllerCreatePlanRequest struct {
	// Identifier of the linked policy.
	PolicyID                       string                                    `pathParam:"style=simple,explode=false,name=policyId"`
	CreatePolicyPlanCommandRequest components.CreatePolicyPlanCommandRequest `request:"mediaType=application/json"`
}

func (o *CreatePolicyPlanCommandControllerCreatePlanRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *CreatePolicyPlanCommandControllerCreatePlanRequest) GetCreatePolicyPlanCommandRequest() components.CreatePolicyPlanCommandRequest {
	if o == nil {
		return components.CreatePolicyPlanCommandRequest{}
	}
	return o.CreatePolicyPlanCommandRequest
}

type CreatePolicyPlanCommandControllerCreatePlanResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	CreatePolicyPlanCommandResponse *components.CreatePolicyPlanCommandResponse
}

func (o *CreatePolicyPlanCommandControllerCreatePlanResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePolicyPlanCommandControllerCreatePlanResponse) GetCreatePolicyPlanCommandResponse() *components.CreatePolicyPlanCommandResponse {
	if o == nil {
		return nil
	}
	return o.CreatePolicyPlanCommandResponse
}
