// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreatePolicyCommandControllerCreatePolicyResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	CreatePolicyCommandResponse *components.CreatePolicyCommandResponse
}

func (o *CreatePolicyCommandControllerCreatePolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePolicyCommandControllerCreatePolicyResponse) GetCreatePolicyCommandResponse() *components.CreatePolicyCommandResponse {
	if o == nil {
		return nil
	}
	return o.CreatePolicyCommandResponse
}
