// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreateAccountControllerCreateAccountResponse struct {
	HTTPMeta              components.HTTPMetadata `json:"-"`
	CreateAccountResponse *components.CreateAccountResponse
}

func (o *CreateAccountControllerCreateAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAccountControllerCreateAccountResponse) GetCreateAccountResponse() *components.CreateAccountResponse {
	if o == nil {
		return nil
	}
	return o.CreateAccountResponse
}
