// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreateRoleAssignmentCommandControllerCreateResponse struct {
	HTTPMeta                     components.HTTPMetadata `json:"-"`
	CreateRoleAssignmentResponse *components.CreateRoleAssignmentResponse
}

func (o *CreateRoleAssignmentCommandControllerCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRoleAssignmentCommandControllerCreateResponse) GetCreateRoleAssignmentResponse() *components.CreateRoleAssignmentResponse {
	if o == nil {
		return nil
	}
	return o.CreateRoleAssignmentResponse
}
