// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type CreateClaimItemCommandControllerCreateRequest struct {
	// Unique identifier of the claim associated with the claim item.
	ClaimID                       string                                   `pathParam:"style=simple,explode=false,name=claimId"`
	CreateClaimItemCommandRequest components.CreateClaimItemCommandRequest `request:"mediaType=application/json"`
}

func (o *CreateClaimItemCommandControllerCreateRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

func (o *CreateClaimItemCommandControllerCreateRequest) GetCreateClaimItemCommandRequest() components.CreateClaimItemCommandRequest {
	if o == nil {
		return components.CreateClaimItemCommandRequest{}
	}
	return o.CreateClaimItemCommandRequest
}

type CreateClaimItemCommandControllerCreateResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	CreateClaimItemCommandResponse *components.CreateClaimItemCommandResponse
}

func (o *CreateClaimItemCommandControllerCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateClaimItemCommandControllerCreateResponse) GetCreateClaimItemCommandResponse() *components.CreateClaimItemCommandResponse {
	if o == nil {
		return nil
	}
	return o.CreateClaimItemCommandResponse
}
