// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type DuplicatePolicyCommandControllerDuplicateRequest struct {
	// Unique identifier of the policy the new policy will be created from.
	PolicyID                      string                                   `pathParam:"style=simple,explode=false,name=policyId"`
	DuplicatePolicyCommandRequest components.DuplicatePolicyCommandRequest `request:"mediaType=application/json"`
}

func (o *DuplicatePolicyCommandControllerDuplicateRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *DuplicatePolicyCommandControllerDuplicateRequest) GetDuplicatePolicyCommandRequest() components.DuplicatePolicyCommandRequest {
	if o == nil {
		return components.DuplicatePolicyCommandRequest{}
	}
	return o.DuplicatePolicyCommandRequest
}

type DuplicatePolicyCommandControllerDuplicateResponse struct {
	HTTPMeta        components.HTTPMetadata `json:"-"`
	PolicyAggregate *components.PolicyAggregate
}

func (o *DuplicatePolicyCommandControllerDuplicateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DuplicatePolicyCommandControllerDuplicateResponse) GetPolicyAggregate() *components.PolicyAggregate {
	if o == nil {
		return nil
	}
	return o.PolicyAggregate
}
