// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
	"github.com/reguardprotection/warrantysphere/models/components"
)

type ListClaimDocumentsQueryControllerListRequest struct {
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Page  *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Value used to search documents by title
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// The feeds of users who can view the document.
	Feed []string `queryParam:"style=form,explode=true,name=feed"`
	// The unique identifier of the claim.
	ClaimID string `pathParam:"style=simple,explode=false,name=claimId"`
}

func (l ListClaimDocumentsQueryControllerListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListClaimDocumentsQueryControllerListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListClaimDocumentsQueryControllerListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListClaimDocumentsQueryControllerListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListClaimDocumentsQueryControllerListRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListClaimDocumentsQueryControllerListRequest) GetFeed() []string {
	if o == nil {
		return nil
	}
	return o.Feed
}

func (o *ListClaimDocumentsQueryControllerListRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

type ListClaimDocumentsQueryControllerListResponse struct {
	HTTPMeta                   components.HTTPMetadata `json:"-"`
	ListDocumentsQueryResponse *components.ListDocumentsQueryResponse
}

func (o *ListClaimDocumentsQueryControllerListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListClaimDocumentsQueryControllerListResponse) GetListDocumentsQueryResponse() *components.ListDocumentsQueryResponse {
	if o == nil {
		return nil
	}
	return o.ListDocumentsQueryResponse
}
