// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
	"github.com/reguardprotection/warrantysphere/models/components"
)

type ListCustomersControllerListRequest struct {
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Page  *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Search query used to filter based on name, email, and phone number.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// List of policy ids used to filter customers who own a warranty created under those policies.
	PolicyIds *string `queryParam:"style=form,explode=true,name=policyIds"`
	// List of distributor ids used to filter customers who own a warranty created under those distributors.
	DistributorIds *string `queryParam:"style=form,explode=true,name=distributorIds"`
}

func (l ListCustomersControllerListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCustomersControllerListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListCustomersControllerListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListCustomersControllerListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListCustomersControllerListRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListCustomersControllerListRequest) GetPolicyIds() *string {
	if o == nil {
		return nil
	}
	return o.PolicyIds
}

func (o *ListCustomersControllerListRequest) GetDistributorIds() *string {
	if o == nil {
		return nil
	}
	return o.DistributorIds
}

type ListCustomersControllerListResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	ListCustomersResponseBody *components.ListCustomersResponseBody
}

func (o *ListCustomersControllerListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListCustomersControllerListResponse) GetListCustomersResponseBody() *components.ListCustomersResponseBody {
	if o == nil {
		return nil
	}
	return o.ListCustomersResponseBody
}
