// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
	"github.com/reguardprotection/warrantysphere/models/components"
)

type ListClaimPaymentsQueryControllerListRequest struct {
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Page  *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// The unique identifier of the user who created the payment.
	CreatedByID *string `queryParam:"style=form,explode=true,name=createdById"`
	// Search string used to filter payment by their title and content.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Unique identifier of the claim used to filter the claim payments.
	ClaimID string `pathParam:"style=simple,explode=false,name=claimId"`
}

func (l ListClaimPaymentsQueryControllerListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListClaimPaymentsQueryControllerListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListClaimPaymentsQueryControllerListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListClaimPaymentsQueryControllerListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListClaimPaymentsQueryControllerListRequest) GetCreatedByID() *string {
	if o == nil {
		return nil
	}
	return o.CreatedByID
}

func (o *ListClaimPaymentsQueryControllerListRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListClaimPaymentsQueryControllerListRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

type ListClaimPaymentsQueryControllerListResponse struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	ListClaimPaymentsResponse *components.ListClaimPaymentsResponse
}

func (o *ListClaimPaymentsQueryControllerListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListClaimPaymentsQueryControllerListResponse) GetListClaimPaymentsResponse() *components.ListClaimPaymentsResponse {
	if o == nil {
		return nil
	}
	return o.ListClaimPaymentsResponse
}
