// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type PolicyQuoteControllerProvisionWarrantyRequest struct {
	// ID of the policy for which to request the quote
	PolicyID               string                            `pathParam:"style=simple,explode=false,name=policyId"`
	PolicyQuoteRequestBody components.PolicyQuoteRequestBody `request:"mediaType=application/json"`
}

func (o *PolicyQuoteControllerProvisionWarrantyRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *PolicyQuoteControllerProvisionWarrantyRequest) GetPolicyQuoteRequestBody() components.PolicyQuoteRequestBody {
	if o == nil {
		return components.PolicyQuoteRequestBody{}
	}
	return o.PolicyQuoteRequestBody
}

type PolicyQuoteControllerProvisionWarrantyResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	PolicyQuoteResponseBody *components.PolicyQuoteResponseBody
}

func (o *PolicyQuoteControllerProvisionWarrantyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PolicyQuoteControllerProvisionWarrantyResponse) GetPolicyQuoteResponseBody() *components.PolicyQuoteResponseBody {
	if o == nil {
		return nil
	}
	return o.PolicyQuoteResponseBody
}
