// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RejectClaimItemCommandControllerRejectRequest struct {
	// Unique identifier of the claim item.
	ItemID string `pathParam:"style=simple,explode=false,name=itemId"`
	// Unique identifier of the claim associated with the claim item.
	ClaimID                       string                                   `pathParam:"style=simple,explode=false,name=claimId"`
	RejectClaimItemCommandRequest components.RejectClaimItemCommandRequest `request:"mediaType=application/json"`
}

func (o *RejectClaimItemCommandControllerRejectRequest) GetItemID() string {
	if o == nil {
		return ""
	}
	return o.ItemID
}

func (o *RejectClaimItemCommandControllerRejectRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

func (o *RejectClaimItemCommandControllerRejectRequest) GetRejectClaimItemCommandRequest() components.RejectClaimItemCommandRequest {
	if o == nil {
		return components.RejectClaimItemCommandRequest{}
	}
	return o.RejectClaimItemCommandRequest
}

type RejectClaimItemCommandControllerRejectResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	RejectClaimItemCommandResponse *components.RejectClaimItemCommandResponse
}

func (o *RejectClaimItemCommandControllerRejectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RejectClaimItemCommandControllerRejectResponse) GetRejectClaimItemCommandResponse() *components.RejectClaimItemCommandResponse {
	if o == nil {
		return nil
	}
	return o.RejectClaimItemCommandResponse
}
