// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type ResolveClaimItemCommandControllerResolveRequest struct {
	// Unique identifier of the claim item.
	ItemID string `pathParam:"style=simple,explode=false,name=itemId"`
	// Unique identifier of the claim associated with the claim item.
	ClaimID                        string                                    `pathParam:"style=simple,explode=false,name=claimId"`
	ResolveClaimItemCommandRequest components.ResolveClaimItemCommandRequest `request:"mediaType=application/json"`
}

func (o *ResolveClaimItemCommandControllerResolveRequest) GetItemID() string {
	if o == nil {
		return ""
	}
	return o.ItemID
}

func (o *ResolveClaimItemCommandControllerResolveRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

func (o *ResolveClaimItemCommandControllerResolveRequest) GetResolveClaimItemCommandRequest() components.ResolveClaimItemCommandRequest {
	if o == nil {
		return components.ResolveClaimItemCommandRequest{}
	}
	return o.ResolveClaimItemCommandRequest
}

type ResolveClaimItemCommandControllerResolveResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	ResolveClaimItemCommandResponse *components.ResolveClaimItemCommandResponse
}

func (o *ResolveClaimItemCommandControllerResolveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ResolveClaimItemCommandControllerResolveResponse) GetResolveClaimItemCommandResponse() *components.ResolveClaimItemCommandResponse {
	if o == nil {
		return nil
	}
	return o.ResolveClaimItemCommandResponse
}
