// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RetrieveStaffPermissionsQueryControllerRetrieveStaffPermissionsRequest struct {
	StaffID string `pathParam:"style=simple,explode=false,name=staffId"`
}

func (o *RetrieveStaffPermissionsQueryControllerRetrieveStaffPermissionsRequest) GetStaffID() string {
	if o == nil {
		return ""
	}
	return o.StaffID
}

type RetrieveStaffPermissionsQueryControllerRetrieveStaffPermissionsResponse struct {
	HTTPMeta                              components.HTTPMetadata `json:"-"`
	RetrieveStaffPermissionsQueryResponse *components.RetrieveStaffPermissionsQueryResponse
}

func (o *RetrieveStaffPermissionsQueryControllerRetrieveStaffPermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveStaffPermissionsQueryControllerRetrieveStaffPermissionsResponse) GetRetrieveStaffPermissionsQueryResponse() *components.RetrieveStaffPermissionsQueryResponse {
	if o == nil {
		return nil
	}
	return o.RetrieveStaffPermissionsQueryResponse
}
