// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RetrieveClaimPaymentQueryControllerRetrieveRequest struct {
	// Unique identifier of the claim used to filter the claim payments.
	ClaimID string `pathParam:"style=simple,explode=false,name=claimId"`
	// Unique identifier of the payment used to filter the claim payments.
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentId"`
}

func (o *RetrieveClaimPaymentQueryControllerRetrieveRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

func (o *RetrieveClaimPaymentQueryControllerRetrieveRequest) GetPaymentID() string {
	if o == nil {
		return ""
	}
	return o.PaymentID
}

type RetrieveClaimPaymentQueryControllerRetrieveResponse struct {
	HTTPMeta              components.HTTPMetadata `json:"-"`
	ClaimPaymentAggregate *components.ClaimPaymentAggregate
}

func (o *RetrieveClaimPaymentQueryControllerRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveClaimPaymentQueryControllerRetrieveResponse) GetClaimPaymentAggregate() *components.ClaimPaymentAggregate {
	if o == nil {
		return nil
	}
	return o.ClaimPaymentAggregate
}
