// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RetrievePaymentQueryControllerRetrievePaymentRequest struct {
	// The unique identifier of the payment.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *RetrievePaymentQueryControllerRetrievePaymentRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type RetrievePaymentQueryControllerRetrievePaymentResponse struct {
	HTTPMeta                components.HTTPMetadata `json:"-"`
	RetrievePaymentResponse *components.RetrievePaymentResponse
}

func (o *RetrievePaymentQueryControllerRetrievePaymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrievePaymentQueryControllerRetrievePaymentResponse) GetRetrievePaymentResponse() *components.RetrievePaymentResponse {
	if o == nil {
		return nil
	}
	return o.RetrievePaymentResponse
}
