// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RetrieveDistributorsSettingsQueryControllerRetrieveDistributorResponse struct {
	HTTPMeta                                    components.HTTPMetadata `json:"-"`
	RetrieveDistributorsSettingsCommandResponse *components.RetrieveDistributorsSettingsCommandResponse
}

func (o *RetrieveDistributorsSettingsQueryControllerRetrieveDistributorResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveDistributorsSettingsQueryControllerRetrieveDistributorResponse) GetRetrieveDistributorsSettingsCommandResponse() *components.RetrieveDistributorsSettingsCommandResponse {
	if o == nil {
		return nil
	}
	return o.RetrieveDistributorsSettingsCommandResponse
}
