// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type RetrievePropertySetJSONControllerRetrieveRequest struct {
	// The unique id of the property set
	SetID string `pathParam:"style=simple,explode=false,name=setId"`
}

func (o *RetrievePropertySetJSONControllerRetrieveRequest) GetSetID() string {
	if o == nil {
		return ""
	}
	return o.SetID
}

type RetrievePropertySetJSONControllerRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *RetrievePropertySetJSONControllerRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
