// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type UpdateAccountControllerUpdateAccountRequest struct {
	// Unique identifier of the account
	ID               string                      `pathParam:"style=simple,explode=false,name=id"`
	UpdateAccountDto components.UpdateAccountDto `request:"mediaType=application/json"`
}

func (o *UpdateAccountControllerUpdateAccountRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAccountControllerUpdateAccountRequest) GetUpdateAccountDto() components.UpdateAccountDto {
	if o == nil {
		return components.UpdateAccountDto{}
	}
	return o.UpdateAccountDto
}

type UpdateAccountControllerUpdateAccountResponse struct {
	HTTPMeta              components.HTTPMetadata `json:"-"`
	UpdateAccountResponse *components.UpdateAccountResponse
}

func (o *UpdateAccountControllerUpdateAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAccountControllerUpdateAccountResponse) GetUpdateAccountResponse() *components.UpdateAccountResponse {
	if o == nil {
		return nil
	}
	return o.UpdateAccountResponse
}
