// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type UpdatePolicyPlanCommandControllerUpdateRequest struct {
	// Unique identifier of the wpolicylan.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
	// Unique identifier of the plan.
	PlanID                         string                                    `pathParam:"style=simple,explode=false,name=planId"`
	UpdatePolicyPlanCommandRequest components.UpdatePolicyPlanCommandRequest `request:"mediaType=application/json"`
}

func (o *UpdatePolicyPlanCommandControllerUpdateRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *UpdatePolicyPlanCommandControllerUpdateRequest) GetPlanID() string {
	if o == nil {
		return ""
	}
	return o.PlanID
}

func (o *UpdatePolicyPlanCommandControllerUpdateRequest) GetUpdatePolicyPlanCommandRequest() components.UpdatePolicyPlanCommandRequest {
	if o == nil {
		return components.UpdatePolicyPlanCommandRequest{}
	}
	return o.UpdatePolicyPlanCommandRequest
}

type UpdatePolicyPlanCommandControllerUpdateResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	UpdatePolicyPlanCommandResponse *components.UpdatePolicyPlanCommandResponse
}

func (o *UpdatePolicyPlanCommandControllerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePolicyPlanCommandControllerUpdateResponse) GetUpdatePolicyPlanCommandResponse() *components.UpdatePolicyPlanCommandResponse {
	if o == nil {
		return nil
	}
	return o.UpdatePolicyPlanCommandResponse
}
