// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type UpdateClaimDocumentControllerUpdateRequest struct {
	// The unique identifier of the claim.
	ClaimID string `pathParam:"style=simple,explode=false,name=claimId"`
	// The unique identifier of the document.
	DocumentID              string                             `pathParam:"style=simple,explode=false,name=documentId"`
	UpdateClaimDocumentBody components.UpdateClaimDocumentBody `request:"mediaType=application/json"`
}

func (o *UpdateClaimDocumentControllerUpdateRequest) GetClaimID() string {
	if o == nil {
		return ""
	}
	return o.ClaimID
}

func (o *UpdateClaimDocumentControllerUpdateRequest) GetDocumentID() string {
	if o == nil {
		return ""
	}
	return o.DocumentID
}

func (o *UpdateClaimDocumentControllerUpdateRequest) GetUpdateClaimDocumentBody() components.UpdateClaimDocumentBody {
	if o == nil {
		return components.UpdateClaimDocumentBody{}
	}
	return o.UpdateClaimDocumentBody
}

type UpdateClaimDocumentControllerUpdateResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	UpdateClaimDocumentResponse *components.UpdateClaimDocumentResponse
}

func (o *UpdateClaimDocumentControllerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateClaimDocumentControllerUpdateResponse) GetUpdateClaimDocumentResponse() *components.UpdateClaimDocumentResponse {
	if o == nil {
		return nil
	}
	return o.UpdateClaimDocumentResponse
}
