// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type UpdatePolicyCommandControllerUpdatePolicyRequest struct {
	// Unique identifier of the policy.
	PolicyID                   string                                `pathParam:"style=simple,explode=false,name=policyId"`
	UpdatePolicyCommandRequest components.UpdatePolicyCommandRequest `request:"mediaType=application/json"`
}

func (o *UpdatePolicyCommandControllerUpdatePolicyRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *UpdatePolicyCommandControllerUpdatePolicyRequest) GetUpdatePolicyCommandRequest() components.UpdatePolicyCommandRequest {
	if o == nil {
		return components.UpdatePolicyCommandRequest{}
	}
	return o.UpdatePolicyCommandRequest
}

type UpdatePolicyCommandControllerUpdatePolicyResponse struct {
	HTTPMeta                    components.HTTPMetadata `json:"-"`
	UpdatePolicyCommandResponse *components.UpdatePolicyCommandResponse
}

func (o *UpdatePolicyCommandControllerUpdatePolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePolicyCommandControllerUpdatePolicyResponse) GetUpdatePolicyCommandResponse() *components.UpdatePolicyCommandResponse {
	if o == nil {
		return nil
	}
	return o.UpdatePolicyCommandResponse
}
