// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/reguardprotection/warrantysphere/models/components"
)

type UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepRequest struct {
	// Unique identifier of the policy.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
	// List of permission keys
	XWspherePermissionKeys                 *string                                           `header:"style=simple,explode=false,name=X-WSPHERE-PERMISSION-KEYS"`
	UpdateClaimLifecycleStepCommandRequest components.UpdateClaimLifecycleStepCommandRequest `request:"mediaType=application/json"`
}

func (o *UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepRequest) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepRequest) GetXWspherePermissionKeys() *string {
	if o == nil {
		return nil
	}
	return o.XWspherePermissionKeys
}

func (o *UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepRequest) GetUpdateClaimLifecycleStepCommandRequest() components.UpdateClaimLifecycleStepCommandRequest {
	if o == nil {
		return components.UpdateClaimLifecycleStepCommandRequest{}
	}
	return o.UpdateClaimLifecycleStepCommandRequest
}

type UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepResponse struct {
	HTTPMeta                                components.HTTPMetadata `json:"-"`
	UpdateClaimLifecycleStepCommandResponse *components.UpdateClaimLifecycleStepCommandResponse
}

func (o *UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateClaimLifecycleStepCommandControllerUpdateClaimLifecycleStepResponse) GetUpdateClaimLifecycleStepCommandResponse() *components.UpdateClaimLifecycleStepCommandResponse {
	if o == nil {
		return nil
	}
	return o.UpdateClaimLifecycleStepCommandResponse
}
