// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
	"time"
)

type ActivateWarrantyCommandRequestBody struct {
	// House possession date.
	TransactionCloseDate time.Time `json:"transactionCloseDate"`
}

func (a ActivateWarrantyCommandRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivateWarrantyCommandRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ActivateWarrantyCommandRequestBody) GetTransactionCloseDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.TransactionCloseDate
}
