// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/reguardprotection/warrantysphere/internal/utils"
)

// ClaimLifecycleStepDtoStatus - The default status of the step seen by the customer when a claim is opened.
type ClaimLifecycleStepDtoStatus string

const (
	ClaimLifecycleStepDtoStatusNotStartedYet   ClaimLifecycleStepDtoStatus = "NOT_STARTED_YET"
	ClaimLifecycleStepDtoStatusDone            ClaimLifecycleStepDtoStatus = "DONE"
	ClaimLifecycleStepDtoStatusInProgress      ClaimLifecycleStepDtoStatus = "IN_PROGRESS"
	ClaimLifecycleStepDtoStatusPendingCustomer ClaimLifecycleStepDtoStatus = "PENDING_CUSTOMER"
	ClaimLifecycleStepDtoStatusUnsuccessful    ClaimLifecycleStepDtoStatus = "UNSUCCESSFUL"
	ClaimLifecycleStepDtoStatusSkipped         ClaimLifecycleStepDtoStatus = "SKIPPED"
)

func (e ClaimLifecycleStepDtoStatus) ToPointer() *ClaimLifecycleStepDtoStatus {
	return &e
}
func (e *ClaimLifecycleStepDtoStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_STARTED_YET":
		fallthrough
	case "DONE":
		fallthrough
	case "IN_PROGRESS":
		fallthrough
	case "PENDING_CUSTOMER":
		fallthrough
	case "UNSUCCESSFUL":
		fallthrough
	case "SKIPPED":
		*e = ClaimLifecycleStepDtoStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClaimLifecycleStepDtoStatus: %v", v)
	}
}

type ClaimLifecycleStepDto struct {
	// The unique identifier of the claim lifecycle step.
	ID *string `json:"id,omitempty"`
	// The position that this step should occur in the claim lifecycle.
	Order *float64 `json:"order,omitempty"`
	// The icon used for the claim lifecycle step.
	Icon string `json:"icon"`
	// The title of the claim lifecycle step.
	Title string `json:"title"`
	// The description of the claim lifecycle step.
	Description string `json:"description"`
	// The default status of the step seen by the customer when a claim is opened.
	Status *ClaimLifecycleStepDtoStatus `default:"NOT_STARTED_YET" json:"status"`
	// Wether or not this step is optional for the customer.
	Optional *bool `default:"false" json:"optional"`
}

func (c ClaimLifecycleStepDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClaimLifecycleStepDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClaimLifecycleStepDto) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ClaimLifecycleStepDto) GetOrder() *float64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *ClaimLifecycleStepDto) GetIcon() string {
	if o == nil {
		return ""
	}
	return o.Icon
}

func (o *ClaimLifecycleStepDto) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ClaimLifecycleStepDto) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *ClaimLifecycleStepDto) GetStatus() *ClaimLifecycleStepDtoStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ClaimLifecycleStepDto) GetOptional() *bool {
	if o == nil {
		return nil
	}
	return o.Optional
}
