// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CoverageConfigDto struct {
	// Unique identifier of the coverage config.
	CoverageID string `json:"coverageId"`
	// The requirement rule for the coverage.
	Requirement RuleDto `json:"requirement"`
	// The deductible rule for the coverage.
	Deductible RuleDto `json:"deductible"`
	// The liability limit rule for the coverage.
	LiabilityLimit RuleDto `json:"liabilityLimit"`
	// The retail price rule for the coverage.
	Price RuleDto `json:"price"`
	// The liability groups rule for the coverage.
	LiabilityGroups RuleDto `json:"liabilityGroups"`
}

func (o *CoverageConfigDto) GetCoverageID() string {
	if o == nil {
		return ""
	}
	return o.CoverageID
}

func (o *CoverageConfigDto) GetRequirement() RuleDto {
	if o == nil {
		return RuleDto{}
	}
	return o.Requirement
}

func (o *CoverageConfigDto) GetDeductible() RuleDto {
	if o == nil {
		return RuleDto{}
	}
	return o.Deductible
}

func (o *CoverageConfigDto) GetLiabilityLimit() RuleDto {
	if o == nil {
		return RuleDto{}
	}
	return o.LiabilityLimit
}

func (o *CoverageConfigDto) GetPrice() RuleDto {
	if o == nil {
		return RuleDto{}
	}
	return o.Price
}

func (o *CoverageConfigDto) GetLiabilityGroups() RuleDto {
	if o == nil {
		return RuleDto{}
	}
	return o.LiabilityGroups
}
