// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePolicyCancelationRuleCommandResponse struct {
	Country string `json:"country"`
	State   string `json:"state"`
}

func (o *CreatePolicyCancelationRuleCommandResponse) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *CreatePolicyCancelationRuleCommandResponse) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}
