// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePaymentScheduleDto struct {
	// Unique identifier of the payment schedule.
	ID string `json:"id"`
	// Title of the payment schedule.
	Title string `json:"title"`
	// Percentage rate at which each installment is adjusted by.
	Rate float64 `json:"rate"`
	// Number of installments payment will be made in.
	Installments float64 `json:"installments"`
}

func (o *CreatePaymentScheduleDto) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreatePaymentScheduleDto) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *CreatePaymentScheduleDto) GetRate() float64 {
	if o == nil {
		return 0.0
	}
	return o.Rate
}

func (o *CreatePaymentScheduleDto) GetInstallments() float64 {
	if o == nil {
		return 0.0
	}
	return o.Installments
}
