// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePropertySetCommandResponse struct {
	// The unique id of the property set
	ID string `json:"id"`
}

func (o *CreatePropertySetCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
