// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDistributorCommandResponse struct {
	// Unique identifier of the distributor.
	ID string `json:"id"`
}

func (o *CreateDistributorCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
