// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDocumentDto struct {
	// Title of the document. Either 'Terms & Conditions' or 'Coverage Summary'.
	Title string `json:"title"`
	// Legal introduction for this document.
	LegalIntroduction *string `json:"legalIntroduction,omitempty"`
	// Welcome introduction for this document.
	WelcomeIntroduction *string `json:"welcomeIntroduction,omitempty"`
	// Definitions for this document.
	Definitions *string `json:"definitions,omitempty"`
	// Document pdf file if a file is to be uploaded.
	UploadFile *bool `json:"uploadFile,omitempty"`
}

func (o *CreateDocumentDto) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *CreateDocumentDto) GetLegalIntroduction() *string {
	if o == nil {
		return nil
	}
	return o.LegalIntroduction
}

func (o *CreateDocumentDto) GetWelcomeIntroduction() *string {
	if o == nil {
		return nil
	}
	return o.WelcomeIntroduction
}

func (o *CreateDocumentDto) GetDefinitions() *string {
	if o == nil {
		return nil
	}
	return o.Definitions
}

func (o *CreateDocumentDto) GetUploadFile() *bool {
	if o == nil {
		return nil
	}
	return o.UploadFile
}
