// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
)

// CreateObjectPropertyRequestConfig - The extra configuration of this property
type CreateObjectPropertyRequestConfig struct {
}

type CreateObjectPropertyRequest struct {
	// The visible name of the property
	Name string `json:"name"`
	// The key of this property. Only lowercase and no special characters or spaces
	ValueKey string `json:"valueKey"`
	// The formId
	FormID *string `default:"null" json:"formId"`
	// The extra configuration of this property
	Config CreateObjectPropertyRequestConfig `json:"config"`
	// The properties and their configuration of this object
	Properties []CreateObjectPropertyAssignmentRequest `json:"properties"`
}

func (c CreateObjectPropertyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateObjectPropertyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateObjectPropertyRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateObjectPropertyRequest) GetValueKey() string {
	if o == nil {
		return ""
	}
	return o.ValueKey
}

func (o *CreateObjectPropertyRequest) GetFormID() *string {
	if o == nil {
		return nil
	}
	return o.FormID
}

func (o *CreateObjectPropertyRequest) GetConfig() CreateObjectPropertyRequestConfig {
	if o == nil {
		return CreateObjectPropertyRequestConfig{}
	}
	return o.Config
}

func (o *CreateObjectPropertyRequest) GetProperties() []CreateObjectPropertyAssignmentRequest {
	if o == nil {
		return []CreateObjectPropertyAssignmentRequest{}
	}
	return o.Properties
}
