// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateAssetCommandRequestBody struct {
	// The unique identifier of the customer
	CustomerID string `json:"customerId"`
	// The unique reference identifier of the asset
	ReferenceID *string `json:"referenceId,omitempty"`
	// The name of the asset
	Name *string `json:"name,omitempty"`
	// The description of the asset
	Description *string `json:"description,omitempty"`
	// The property set and property values of the asset
	Submission CreatePropertySetSubmissionCommandRequest `json:"submission"`
}

func (o *CreateAssetCommandRequestBody) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *CreateAssetCommandRequestBody) GetReferenceID() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceID
}

func (o *CreateAssetCommandRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateAssetCommandRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateAssetCommandRequestBody) GetSubmission() CreatePropertySetSubmissionCommandRequest {
	if o == nil {
		return CreatePropertySetSubmissionCommandRequest{}
	}
	return o.Submission
}
