// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Headers - Optional headers for the webhook to use for its callback
type Headers struct {
}

type CreateWebhookRequest struct {
	// Callback url for the webhook to call on events. Requires HTTPS url
	URL string `json:"url"`
	// API events that will trigger the webhook. Optional, defaults to all events.
	EventTypes []string `json:"eventTypes,omitempty"`
	// Webhook will only trigger when event involves given distributors. Optional, defaults to all distributors.
	DistributorIds []string `json:"distributorIds,omitempty"`
	// Optional headers for the webhook to use for its callback
	Headers *Headers `json:"headers,omitempty"`
}

func (o *CreateWebhookRequest) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *CreateWebhookRequest) GetEventTypes() []string {
	if o == nil {
		return nil
	}
	return o.EventTypes
}

func (o *CreateWebhookRequest) GetDistributorIds() []string {
	if o == nil {
		return nil
	}
	return o.DistributorIds
}

func (o *CreateWebhookRequest) GetHeaders() *Headers {
	if o == nil {
		return nil
	}
	return o.Headers
}
