// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateClaimNoteCommandResponse struct {
	// Unique identifier of the note.
	ID string `json:"id"`
}

func (o *CreateClaimNoteCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
