// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDocumentProcessorRunResponse struct {
	// Unique identifier of the processor run that was created.
	ID string `json:"id"`
}

func (o *CreateDocumentProcessorRunResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
