// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/reguardprotection/warrantysphere/internal/utils"
	"time"
)

// CustomerAggregateAddress - Shipping address of the customer
type CustomerAggregateAddress struct {
	Line1   string  `json:"line1"`
	Line2   *string `json:"line2"`
	Zip     string  `json:"zip"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	Country string  `json:"country"`
}

func (o *CustomerAggregateAddress) GetLine1() string {
	if o == nil {
		return ""
	}
	return o.Line1
}

func (o *CustomerAggregateAddress) GetLine2() *string {
	if o == nil {
		return nil
	}
	return o.Line2
}

func (o *CustomerAggregateAddress) GetZip() string {
	if o == nil {
		return ""
	}
	return o.Zip
}

func (o *CustomerAggregateAddress) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *CustomerAggregateAddress) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}

func (o *CustomerAggregateAddress) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

type CustomerAggregate struct {
	// Unique identifier for the customer.
	ID string `json:"id"`
	// User-defined reference ID.
	ReferenceID *string `json:"referenceId"`
	// The customer's full name.
	Name string `json:"name"`
	// The customer's email address.
	Email string `json:"email"`
	// The customer's phone number.
	Phone *string `json:"phone"`
	// Unique identifier for the user.
	UserID string `json:"userId"`
	// User linked to the customer.
	User *UserAggregate `json:"user,omitempty"`
	// Datetime when the object was created.
	Created time.Time `json:"created"`
	// Datetime when the object was last modified.
	Modified time.Time `json:"modified"`
	// Shipping address of the customer
	Address *CustomerAggregateAddress `json:"address"`
	// JSON object of metadata related to the customer.
	Metadata *string `json:"metadata"`
}

func (c CustomerAggregate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerAggregate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CustomerAggregate) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CustomerAggregate) GetReferenceID() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceID
}

func (o *CustomerAggregate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CustomerAggregate) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *CustomerAggregate) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *CustomerAggregate) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *CustomerAggregate) GetUser() *UserAggregate {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *CustomerAggregate) GetCreated() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Created
}

func (o *CustomerAggregate) GetModified() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Modified
}

func (o *CustomerAggregate) GetAddress() *CustomerAggregateAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *CustomerAggregate) GetMetadata() *string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
