// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeactivateDistributorCommandResponseStatus - The status of the distributor after being deactivated.
type DeactivateDistributorCommandResponseStatus struct {
}

type DeactivateDistributorCommandResponse struct {
	// Unique identifier of the distributor.
	ID string `json:"id"`
	// The status of the distributor after being deactivated.
	Status DeactivateDistributorCommandResponseStatus `json:"status"`
}

func (o *DeactivateDistributorCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeactivateDistributorCommandResponse) GetStatus() DeactivateDistributorCommandResponseStatus {
	if o == nil {
		return DeactivateDistributorCommandResponseStatus{}
	}
	return o.Status
}
