// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteDocumentResponse struct {
	// Unique identifier of the document.
	ID string `json:"id"`
}

func (o *DeleteDocumentResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
