// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteAssetCommandResponse struct {
	// The unique identifier of the asset
	AssetID string `json:"assetId"`
}

func (o *DeleteAssetCommandResponse) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}
