// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DisableAPIKeyResponse struct {
	ID string `json:"id"`
}

func (o *DisableAPIKeyResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
