// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EvaluatedPlan struct {
	// The unique identifier of the plan
	ID              string                `json:"id"`
	Plan            PolicyPlanAggregate   `json:"plan"`
	ApplicableTerms []EvaluatedPolicyTerm `json:"applicableTerms"`
}

func (o *EvaluatedPlan) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *EvaluatedPlan) GetPlan() PolicyPlanAggregate {
	if o == nil {
		return PolicyPlanAggregate{}
	}
	return o.Plan
}

func (o *EvaluatedPlan) GetApplicableTerms() []EvaluatedPolicyTerm {
	if o == nil {
		return []EvaluatedPolicyTerm{}
	}
	return o.ApplicableTerms
}
