// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FinalizeWarrantyCommandResponse struct {
	// Unique identifier of the warranty.
	ID string `json:"id"`
}

func (o *FinalizeWarrantyCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
