// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListClaimPaymentsResponse struct {
	Meta  PaginationMeta          `json:"meta"`
	Items []ClaimPaymentAggregate `json:"items"`
}

func (o *ListClaimPaymentsResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListClaimPaymentsResponse) GetItems() []ClaimPaymentAggregate {
	if o == nil {
		return []ClaimPaymentAggregate{}
	}
	return o.Items
}
