// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAssetsQueryResponse struct {
	Meta  PaginationMeta   `json:"meta"`
	Items []AssetAggregate `json:"items"`
}

func (o *ListAssetsQueryResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListAssetsQueryResponse) GetItems() []AssetAggregate {
	if o == nil {
		return []AssetAggregate{}
	}
	return o.Items
}
