// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListCustomersResponseBody struct {
	Meta  PaginationMeta      `json:"meta"`
	Items []CustomerAggregate `json:"items"`
}

func (o *ListCustomersResponseBody) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListCustomersResponseBody) GetItems() []CustomerAggregate {
	if o == nil {
		return []CustomerAggregate{}
	}
	return o.Items
}
