// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListDocumentsQueryResponse struct {
	Meta  PaginationMeta      `json:"meta"`
	Items []DocumentAggregate `json:"items"`
}

func (o *ListDocumentsQueryResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListDocumentsQueryResponse) GetItems() []DocumentAggregate {
	if o == nil {
		return []DocumentAggregate{}
	}
	return o.Items
}
