// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListCoveragesQueryResponse struct {
	Meta  PaginationMeta      `json:"meta"`
	Items []CoverageAggregate `json:"items"`
}

func (o *ListCoveragesQueryResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListCoveragesQueryResponse) GetItems() []CoverageAggregate {
	if o == nil {
		return []CoverageAggregate{}
	}
	return o.Items
}
