// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListPaymentsResponse struct {
	Meta  PaginationMeta     `json:"meta"`
	Items []PaymentAggregate `json:"items"`
}

func (o *ListPaymentsResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListPaymentsResponse) GetItems() []PaymentAggregate {
	if o == nil {
		return []PaymentAggregate{}
	}
	return o.Items
}
