// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListClaimItemsQueryResponse struct {
	Meta  PaginationMeta   `json:"meta"`
	Items []ClaimAggregate `json:"items"`
}

func (o *ListClaimItemsQueryResponse) GetMeta() PaginationMeta {
	if o == nil {
		return PaginationMeta{}
	}
	return o.Meta
}

func (o *ListClaimItemsQueryResponse) GetItems() []ClaimAggregate {
	if o == nil {
		return []ClaimAggregate{}
	}
	return o.Items
}
