// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PolicyQuoteResponseBody struct {
	// The unique identifier of the published policy the plans belong too
	PolicyID        string          `json:"policyId"`
	ApplicablePlans []EvaluatedPlan `json:"applicablePlans"`
}

func (o *PolicyQuoteResponseBody) GetPolicyID() string {
	if o == nil {
		return ""
	}
	return o.PolicyID
}

func (o *PolicyQuoteResponseBody) GetApplicablePlans() []EvaluatedPlan {
	if o == nil {
		return []EvaluatedPlan{}
	}
	return o.ApplicablePlans
}
