// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RedraftClaimItemCommandRequest struct {
	// Reasoning as to why the claim item was marked as draft.
	Reason *string `json:"reason"`
}

func (o *RedraftClaimItemCommandRequest) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}
