// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResolveClaimItemCommandResponse struct {
	// Unique identifier of the claim item.
	ID string `json:"id"`
}

func (o *ResolveClaimItemCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
