// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RetryPaymentResponseStatus - The status of the retried payment
type RetryPaymentResponseStatus struct {
}

type RetryPaymentResponse struct {
	// The unique identifier of the payment.
	PaymentID string `json:"paymentId"`
	// The status of the retried payment
	Status RetryPaymentResponseStatus `json:"status"`
}

func (o *RetryPaymentResponse) GetPaymentID() string {
	if o == nil {
		return ""
	}
	return o.PaymentID
}

func (o *RetryPaymentResponse) GetStatus() RetryPaymentResponseStatus {
	if o == nil {
		return RetryPaymentResponseStatus{}
	}
	return o.Status
}
