// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SelfServeInvoicePackage struct {
}

type RetrieveDistributorsSettingsCommandResponse struct {
	// Setting allowing users to be registered from distributor onboarding.
	CanRegisterUsers        bool                    `json:"canRegisterUsers"`
	SelfServeInvoicePackage SelfServeInvoicePackage `json:"selfServeInvoicePackage"`
}

func (o *RetrieveDistributorsSettingsCommandResponse) GetCanRegisterUsers() bool {
	if o == nil {
		return false
	}
	return o.CanRegisterUsers
}

func (o *RetrieveDistributorsSettingsCommandResponse) GetSelfServeInvoicePackage() SelfServeInvoicePackage {
	if o == nil {
		return SelfServeInvoicePackage{}
	}
	return o.SelfServeInvoicePackage
}
