// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RetrieveAssetQueryResponseValues - The values of the most recent asset submission
type RetrieveAssetQueryResponseValues struct {
}

type RetrieveAssetQueryResponse struct {
	// Unique identifier of the asset.
	ID string `json:"id"`
	// User-defined reference ID.
	ReferenceID *string `json:"referenceId"`
	// Display name of the asset.
	Name string `json:"name"`
	// Short description of the asset.
	Description *string `json:"description"`
	// The unique identifier of the property set
	PropertySetID string               `json:"propertySetId"`
	PropertySet   PropertySetAggregate `json:"propertySet"`
	CustomerID    string               `json:"customerId"`
	Customer      CustomerAggregate    `json:"customer"`
	Submissions   []string             `json:"submissions"`
	// The values of the most recent asset submission
	Values RetrieveAssetQueryResponseValues `json:"values"`
}

func (o *RetrieveAssetQueryResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveAssetQueryResponse) GetReferenceID() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceID
}

func (o *RetrieveAssetQueryResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RetrieveAssetQueryResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RetrieveAssetQueryResponse) GetPropertySetID() string {
	if o == nil {
		return ""
	}
	return o.PropertySetID
}

func (o *RetrieveAssetQueryResponse) GetPropertySet() PropertySetAggregate {
	if o == nil {
		return PropertySetAggregate{}
	}
	return o.PropertySet
}

func (o *RetrieveAssetQueryResponse) GetCustomerID() string {
	if o == nil {
		return ""
	}
	return o.CustomerID
}

func (o *RetrieveAssetQueryResponse) GetCustomer() CustomerAggregate {
	if o == nil {
		return CustomerAggregate{}
	}
	return o.Customer
}

func (o *RetrieveAssetQueryResponse) GetSubmissions() []string {
	if o == nil {
		return []string{}
	}
	return o.Submissions
}

func (o *RetrieveAssetQueryResponse) GetValues() RetrieveAssetQueryResponseValues {
	if o == nil {
		return RetrieveAssetQueryResponseValues{}
	}
	return o.Values
}
