// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DefaultValue - Default value to be used if none of the block conditions are met
type DefaultValue struct {
}

type RuleDto struct {
	// List of condition blocks or condition groups
	Blocks []string `json:"blocks"`
	// Default value to be used if none of the block conditions are met
	DefaultValue DefaultValue `json:"defaultValue"`
	// Path to the property value for the default value. Actual value determined by the customer asset
	ValuePropertyPath string `json:"valuePropertyPath"`
}

func (o *RuleDto) GetBlocks() []string {
	if o == nil {
		return []string{}
	}
	return o.Blocks
}

func (o *RuleDto) GetDefaultValue() DefaultValue {
	if o == nil {
		return DefaultValue{}
	}
	return o.DefaultValue
}

func (o *RuleDto) GetValuePropertyPath() string {
	if o == nil {
		return ""
	}
	return o.ValuePropertyPath
}
