// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SetPlanVisibilityCommandRequest struct {
	Visible bool `json:"visible"`
}

func (o *SetPlanVisibilityCommandRequest) GetVisible() bool {
	if o == nil {
		return false
	}
	return o.Visible
}
