// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateStaffResponse struct {
	// Unique id of a staff memeber
	ID string `json:"id"`
}

func (o *UpdateStaffResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
