// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateNoteCommandResponse struct {
	ID string `json:"id"`
}

func (o *UpdateNoteCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
