// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdatePortalConfigResponseConfig - The updated config for the organization
type UpdatePortalConfigResponseConfig struct {
}

type UpdatePortalConfigResponse struct {
	// The updated config for the organization
	Config UpdatePortalConfigResponseConfig `json:"config"`
	// Tenant logo.
	LogoUploadURL string `json:"logoUploadUrl"`
	// Tenant avatar.
	AvatarUploadURL string `json:"avatarUploadUrl"`
}

func (o *UpdatePortalConfigResponse) GetConfig() UpdatePortalConfigResponseConfig {
	if o == nil {
		return UpdatePortalConfigResponseConfig{}
	}
	return o.Config
}

func (o *UpdatePortalConfigResponse) GetLogoUploadURL() string {
	if o == nil {
		return ""
	}
	return o.LogoUploadURL
}

func (o *UpdatePortalConfigResponse) GetAvatarUploadURL() string {
	if o == nil {
		return ""
	}
	return o.AvatarUploadURL
}
