// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateNoteCommandRequest struct {
	// The title of the note.
	Title *string `json:"title,omitempty"`
	// The content associated with the note.
	Content *string `json:"content,omitempty"`
	// The feeds of users who can view the note.
	Feed [][]string `json:"feed,omitempty"`
}

func (o *UpdateNoteCommandRequest) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UpdateNoteCommandRequest) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *UpdateNoteCommandRequest) GetFeed() [][]string {
	if o == nil {
		return nil
	}
	return o.Feed
}
