// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDocumentResponse struct {
	// Unique identifier of the document.
	ID string `json:"id"`
}

func (o *UpdateDocumentResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
