// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateClaimPaymentCommandRequest struct {
	// The title of the payment.
	Title *string `json:"title,omitempty"`
	// Long description of the payment
	Description *string `json:"description,omitempty"`
	// Unique ID of the payment in its payment method's associated gateway
	Destination *string `json:"destination,omitempty"`
	// The monetary amount of the deductible to be paid for any claim.
	//                   A positive integer representing how much to charge in the smallest currency unit (e.g. 100 cents to charge $1.00).
	//                   If not 0, the minimum amount is 50 ($0.50).
	Amount *int64 `json:"amount,omitempty"`
}

func (o *UpdateClaimPaymentCommandRequest) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UpdateClaimPaymentCommandRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateClaimPaymentCommandRequest) GetDestination() *string {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *UpdateClaimPaymentCommandRequest) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}
