// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdatePolicyEmailCommandResponse struct {
	// Unique identifier of the policy email.
	ID string `json:"id"`
}

func (o *UpdatePolicyEmailCommandResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
