// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDistributorCommandRequest struct {
	// Name of the distributor.
	Name string `json:"name"`
	// Email of the distributor.
	Email *string `json:"email,omitempty"`
	// Phone number of the distributor.
	Phone *string `json:"phone,omitempty"`
}

func (o *UpdateDistributorCommandRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateDistributorCommandRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateDistributorCommandRequest) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}
